version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_data:/app/static
      - media_data:/app/media

  caddy:
    image: caddy:latest
    container_name: caddy_server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static_data:/app/static
      - media_data:/app/media
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  static_data:
  media_data:
  caddy_data:
  caddy_config:

